### ISSUE TITLE
Design database

### ISSUE THREAD

**Issue by dungntm58** [dungntm58/BigBirdsProject#1]
Như đã bàn bạc thì anh em khẩn trương up bản thiết kế database để hoàn thành một số chức năng trong order

**Comment by linhlq58** [comment]
bản thiết kế gồm những gì nhỉ

**Comment by linhlq58** [comment]
ơ mà thấy trên drive có rồi cơ mà :)))

**Comment by dungntm58** [comment]
có trong design database trên dropbox ấy. Ý ở đây là biến bản thiết kế thành file ấy

**Comment by hungnm58** [comment]
đã up database của mình. rồi mọi người vào xem nhé. 
Thịnh: a sẽ sửa thành hướng đối tượng cho giống chú :D

**Comment by thinhnd580** [comment]
ừm ngon r :+1:  cho mấy thằng QA check chết cm chúng nó đê

**Comment by dungntm58** [comment]
đề nghị các thím ăn nói nghiêm túc, topic is opened
